# DataSource settings: set here your own configurations for the database
spring.datasource.url = jdbc:postgresql://spring:5432/spring
spring.datasource.username = spring
spring.datasource.password = spring123#