# DataSource settings: set here your own configurations for the database
spring.datasource.url = jdbc:postgresql://localhost:5432/spring
spring.datasource.username = spring
spring.datasource.password = spring123#
spring.jpa.properties.hibernate.format_sql=true

example.property= I AM DEV